[workspace]
resolver = "2"
members = [
  "crates/client",
  "crates/game",
  "crates/macros",
  "crates/server",
  "crates/worldgen",
]

[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 1

[workspace.dependencies]
bevy = { version = "0.18", default-features = false, features = [
  "std",
  "bevy_winit",
  "bevy_window",
  "bevy_render",
  "bevy_core_pipeline",
  "bevy_pbr",
  "bevy_asset",
  "bevy_log",
  "bevy_ui",
  "bevy_ui_render",
  "bevy_text",
  "default_font",
  "multi_threaded",
  "tonemapping_luts",
  "ktx2",
  "zstd_rust",
  "x11",
  "wayland",
] }
block-mesh = { path = "crates/block-mesh", default-features = false }
game = { path = "crates/game" }
log = { version = "0.4.22", default-features = false }
bincode = { version = "1.3.3", default-features = false }
crossbeam = { version = "0.8.4", features = [
  "std",
  "alloc",
  "crossbeam-channel",
], default-features = false }
serde = { version = "1.0.216", features = ["derive"], default-features = false }
bytemuck = { version = "1.23.2", default-features = false }
borrow = { version = "1.3.0", default-features = false }
float-derive = { version = "0.1.0", default-features = false }
derive_more = { version = "2.0.1", features = [
  "debug",
], default-features = false }
crc32fast = { version = "1.5.0", default-features = false }
simplelog = { version = "0.12.2", default-features = false }
quinn = { version = "0.11.6", features = ["rustls-ring", "runtime-tokio"], default-features = false }
tokio = { version = "1.42.0", features = [
  "rt-multi-thread",
], default-features = false }
arrayvec = { version = "0.7.6", default-features = false }
grid = { version = "1.0.0", default-features = false }
syn = { version = "2.0.106", features = ["full"] }
quote = { version = "1.0.40", default-features = false }
proc-macro2 = { version = "1.0.101", default-features = false }
linkme = { version = "0.3.33", default-features = false }
rcgen = { version = "0.13.2", features = [
  "crypto",
  "ring",
], default-features = false }
dashmap = { version = "6.1.0", default-features = false }
papaya = { version = "0.2.3", default-features = false }
serde_json = "1.0.93"
assert-json-diff = "=2.0.2"
pyroscope = { version = "0.5.8" }
pyroscope_pprofrs = { version = "0.2.10" }
image = { version = "0.25.9", default-features = false, features = ["png"] }
ordered-float = { path = "crates/ordered-float", default-features = false, features = [
  "serde", "bytemuck", "spade"
] }
spade = { version = "2.9", default-features = false, features = ["serde"] }
nalgebra = { path = "crates/nalgebra", default-features = false, features = [
  "alloc",
  "convert-bytemuck",
  "serde-serialize",
  "std",
  "macros",
  "libm"
] }
simba = { path = "crates/simba", default-features = false, features = [
  "libm_force",
] }
approx = { path = "crates/approx", default-features = false }
oorandom = "11.1.5"
ordermap = { version = "1.0.0", features = ["serde"] }
hashbrown = { version = "0.16", default-features = false, features = [
  "default-hasher",
] }
parry3d = { path = "crates/parry/crates/parry3d" }
rapier3d = { path = "crates/rapier/crates/rapier3d", features = ["enhanced-determinism"] }
slotmapd = {path = "crates/slotmapd"}
num-traits = { version = "0.2.11" }
wtransport = { version = "0.7", default-features = false, features = ["self-signed", "ring"] }
