[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
game = { path = "../game" }
slotmapd = { path = "../slotmapd", features = ["serde"] }
simplelog = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
block-mesh = { workspace = true }
ndshape = { workspace = true }
crossbeam = { workspace = true }
bincode = { workspace = true }
crc32fast = { workspace = true }
derive_more = { workspace = true }
weak-table = { workspace = true }
bytemuck = { workspace = true }
futures-lite = { workspace = true }
# pyroscope = { workspace = true }
# pyroscope_pprofrs = { workspace = true }
wgpu = { workspace = true }
pollster = { workspace = true }
winit = { workspace = true }
parley = { workspace = true }
vello = { workspace = true }
kurbo = { workspace = true }
quinn = "0.11.6"
tokio = { version = "1.42.0", features = ["rt-multi-thread"] }
