[package]
name = "client"
version = "0.1.0"
edition = "2021"

[features]
pyroscope = ["dep:pyroscope", "dep:pyroscope_pprofrs"]

[dependencies]
game = { workspace = true }
slotmapd = { workspace = true }
log = { workspace = true }
block-mesh = { workspace = true }
crossbeam = { workspace = true }
bincode = { workspace = true }
pyroscope = { workspace = true, optional = true }
pyroscope_pprofrs = { workspace = true, optional = true }
bevy = { workspace = true }
quinn = { workspace = true }
tokio = { workspace = true }
image = { workspace = true }
rollback = { workspace = true }
ordered-float = { workspace = true }
