use winit::{
    event::{ElementState, MouseButton},
    keyboard::PhysicalKey,
};

use crate::{GameDataRaw, GameDataTransactionKind, UpdateGameData};

pub type Tick = usize;
pub type EventId = usize;
pub type EntityId = usize;
pub type RegionId = usize;
pub type LastGameEventId = usize;

pub enum ClientUpdateEvent {
    NewRegion(GameDataRaw),
    UpdateRegion(RegionId, UpdateGameData, GameDataTransactionKind),
    GameCrash(GameError),
}

#[derive(Debug)]
pub enum GameError {}

pub enum WorldId {
    Default = 0,
}

#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub enum ClientPacket {
    /// Event that tells the server the last executed tick of the client. Can be
    /// used to slow the server down to accomodate slow clients.
    SyncClock,
    /// Game event generated by client that needs to be processed by the server.
    GameEvent(GameEvent),
    RequestRegion,
}

#[derive(serde::Serialize, serde::Deserialize)]
pub enum ServerPacket {
    SyncClock,
    /// Game event that was proccessed by the server.
    GameEvent(GameEvent),
    Region(RegionId, GameDataRaw, LastGameEventId),
}

/// A Game event
#[derive(Debug, Copy, Clone, serde::Serialize, serde::Deserialize, PartialEq)]
pub struct GameEvent {
    /// Type of game event.
    pub kind: GameEventKind,
    pub id: usize,
    pub _region_id: usize,
}

impl Ord for GameEvent {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.id.cmp(&other.id)
    }
}

impl PartialOrd for GameEvent {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(&other))
    }
}

impl Eq for GameEvent {}

impl GameEvent {
    pub fn new(kind: GameEventKind, id: usize, _region_id: usize) -> Self {
        Self {
            kind,
            id,
            _region_id,
        }
    }
}

#[derive(Debug, Copy, Clone, serde::Serialize, serde::Deserialize, PartialEq)]
pub enum GameEventKind {
    Tick,
    MouseEvent(MouseButton, ElementState),
    KeyboardEvent(PhysicalKey, ElementState),
    Quit,
}
