use std::{any::TypeId, collections::BTreeMap, path::PathBuf};

use crate::{
    data::PlayerKey, transaction::GameDataTransactionKind, GameData, Rollback, GameDataUpdate,
};
use derive_more::Debug;
use log::info;
use winit::{
    dpi::{PhysicalPosition, PhysicalSize},
    event::{
        AxisId, ButtonId, ElementState, MouseButton, MouseScrollDelta, RawKeyEvent, TouchPhase,
    },
    keyboard::{self, PhysicalKey},
};

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct Usize {
    data: usize,
}

impl From<usize> for Usize {
    fn from(value: usize) -> Self {
        let mut temp = Self::default();
        temp.data = value;
        temp
    }
}

pub type Tick = usize;
pub type EventId = usize;
pub type EntityId = usize;
pub type RegionId = usize;
pub type LastGameEventId = usize;

#[derive(Debug)]
pub enum GameError {}

pub enum WorldId {
    Default = 0,
}

#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub enum ClientPacket {
    /// Game event generated by client that needs to be processed by the server.
    GameEvent(GameEvent),
    RequestRegion,
}

type CurrentTickRate = u64;

#[derive(serde::Serialize, serde::Deserialize)]
pub enum ServerPacket {
    SyncClock(RegionId, CurrentTickRate, Tick),
    /// Game event that was proccessed by the server.
    GameEvent(GameEvent),
    // TODO: Create player serverside and add player id here to let client know
    // who he is.
    Region(RegionId, Rollback, LastGameEventId, Option<PlayerKey>),
}

/// A Game event
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq)]
pub struct GameEvent {
    /// Type of game event.
    pub kind: GameEventKind,
    pub id: usize,
    pub region_id: usize,
}

impl Ord for GameEvent {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.id.cmp(&other.id)
    }
}

impl PartialOrd for GameEvent {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(&other))
    }
}

impl Eq for GameEvent {}

impl GameEvent {
    pub fn new(kind: GameEventKind, id: usize, _region_id: usize) -> Self {
        Self {
            kind,
            id,
            region_id: _region_id,
        }
    }
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq)]
pub enum WindowEvent {
    KeyboardInput {
        physical_key: PhysicalKey,
        logical_key: keyboard::Key,
        location: keyboard::KeyLocation,
        state: ElementState,
        repeat: bool,
        is_synthetic: bool,
    },
    CursorMoved {
        position: PhysicalPosition<f64>,
    },
    MouseInput {
        state: ElementState,
        button: MouseButton,
    },
    MouseWheel {
        delta: MouseScrollDelta,
        phase: TouchPhase,
    },
    Focused(bool),
    ScaleFactorChanged {
        scale_factor: f64,
    },
    DroppedFile(PathBuf),
    Resized(PhysicalSize<u32>),
    CloseRequested,
    Destroyed,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq)]
pub enum DeviceEvent {
    Added,
    Removed,

    /// Change in physical position of a pointing device.
    ///
    /// This represents raw, unfiltered physical motion. Not to be confused with
    /// [`WindowEvent::CursorMoved`].
    MouseMotion {
        /// (x, y) change in position in unspecified units.
        ///
        /// Different devices may use different units.
        delta: (f64, f64),
    },

    /// Physical scroll event
    MouseWheel {
        delta: MouseScrollDelta,
    },

    /// Motion on some analog axis. This event will be reported for all arbitrary input devices
    /// that winit supports on this platform, including mouse devices.  If the device is a mouse
    /// device then this will be reported alongside the MouseMotion event.
    Motion {
        axis: AxisId,
        value: f64,
    },

    Button {
        button: ButtonId,
        state: ElementState,
    },

    Key(RawKeyEvent),
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq)]
pub enum WinitEvent {
    WindowEvent(WindowEvent),
    DeviceEvent(DeviceEvent),
    NewEvents,
    AboutToWait,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq)]
pub enum GameEventKind {
    Tick,
    PlayerWinitEvent(PlayerKey, WinitEvent),
    Quit,
}
