//! Game simulation code that is shared between client and server.
#![deny(missing_docs)]

mod game_data;
mod models;
pub(crate) mod sql;

use std::collections::VecDeque;

pub use game_data::GameData;
use log::info;
pub(crate) use models::*;
use serde::{Deserialize, Serialize};
pub(crate) use sql::*;

/// Event ID
pub type Tick = usize;
/// Event ID
pub type EventId = usize;

/// An error encountered in the game sim.
#[derive(Debug)]
pub enum GameError {}

/// Region Id
pub enum WorldId {
    /// Games starter area
    StarterArea = 0,
}

/// Network packet that is sent from the client.
#[derive(Debug, Serialize, Deserialize)]
pub enum ClientPacket {
    /// Event that tells the server the last executed tick of the client. Can be
    /// used to slow the server down to accomodate slow clients.
    SyncClock,
    /// Game event generated by client that needs to be processed by the server.
    GameEvent(GameEvent),
}

/// Network packet that is sent from the server.
#[derive(Debug, Serialize, Deserialize)]
pub enum ServerPacket {
    /// Sync clock
    SyncClock,
    /// Game event that was proccessed by the server.
    GameEvent(GameEvent),
}

/// A Game event
#[derive(Debug, Copy, Clone, Serialize, Deserialize)]
pub struct GameEvent {
    /// Type of game event.
    pub kind: GameEventKind,
}

/// Game Event Kind
#[derive(Debug, Copy, Clone, Serialize, Deserialize)]
pub enum GameEventKind {
    /// A game tick
    Tick(Tick),
    /// Change the players direction. Speed should be internal to the game logic
    /// and not set here.
    PlayerChangeDirection(i32, i8, i8),
    /// Stop the game and cleanup.
    Quit,
}

/// A region represents an portion of the world that processes game events
/// at its own rate, without any data dependancies to other parts of the world.
pub struct GameInstance {
    data: GameData,
    log: VecDeque<GameData>,
}

/// Snapshot of the simulation state for the client to render.
pub struct GameSnapshot {
    /// Player
    pub player: Option<Player>,
}

impl GameSnapshot {
    /// Build an empty game snapshot.
    pub fn new() -> Self {
        Self { player: None }
    }

    /// Update the game snapshot with new data from simulation.
    pub fn apply_update(&mut self, update: GameSnapshotUpdate) {}
}

/// Data for incremental update to GameSnapshot
#[derive(Debug)]
pub enum GameSnapshotUpdate {}

impl GameEvent {
    /// New event
    pub fn new(kind: GameEventKind) -> Self {
        Self { kind }
    }
}

impl GameInstance {
    /// Create new region
    pub fn new(id: WorldId, inital_tick: Tick) -> Self {
        let data = GameData::new(inital_tick);
        Self {
            data,
            log: VecDeque::new(),
        }
    }
    /// Check if event from network matches client event history.
    pub fn reconcile(&mut self, _event_id: EventId) -> Result<(), String> {
        Ok(())
    }
    /// Handle a client event.
    pub fn handle_event(&mut self, event: GameEvent) -> Result<(), GameError> {
        info!("Handling: {:?}", event);
        match event.kind {
            GameEventKind::Tick(tick) => {
                let mut t = self.data.transaction(tick);
                t.step_physics().unwrap();
                drop(t);
            }
            GameEventKind::PlayerChangeDirection(_, _, _) => (),
            GameEventKind::Quit => todo!(),
        }
        Ok(())
    }
    fn rollback(&mut self, tick: Tick) -> Result<(), String> {
        Ok(())
    }
}
