//! Game simulation code that is shared between client and server.
// #![deny(missing_docs)]

mod game_data;
mod models;

use std::{
    cmp::Reverse,
    collections::{BTreeMap, BinaryHeap, VecDeque},
    sync::{Arc, Mutex, MutexGuard},
};

use log::info;
use parley::{FontContext, LayoutContext};
use rapier3d::na::Vector3;
use serde::{Deserialize, Serialize};

use crate::game_data::text_layout;
pub use crate::game_data::Entity;
pub use crate::game_data::EntityType;
pub use game_data::{GameData, RegionData};

/// Game Tick
pub type Tick = usize;
/// Game Event ID
pub type EventId = usize;
/// Entity ID
pub type EntityId = usize;

/// Event sent from game to client
pub enum ClientUpdateEvent {
    /// Update the game client with new sim info.
    Region(Arc<Mutex<RegionData>>),
    /// Notify client of game crashing.
    GameCrash(GameError),
}

/// An error encountered in the game sim.
#[derive(Debug)]
pub enum GameError {}

pub enum WorldId {
    /// Games starter area
    StarterArea = 0,
}

/// Network packet that is sent from the client.
#[derive(Debug, Serialize, Deserialize)]
pub enum ClientPacket {
    /// Event that tells the server the last executed tick of the client. Can be
    /// used to slow the server down to accomodate slow clients.
    SyncClock,
    /// Game event generated by client that needs to be processed by the server.
    GameEvent(GameEvent),
    RequestRegion,
}

type RegionId = usize;
type LastGameEventId = usize;

/// Network packet that is sent from the server.
#[derive(Serialize, Deserialize)]
pub enum ServerPacket {
    /// Sync clock
    SyncClock,
    /// Game event that was proccessed by the server.
    GameEvent(GameEvent),
    Region(RegionId, GameData, LastGameEventId),
}

/// A Game event
#[derive(Debug, Copy, Clone, Serialize, Deserialize, PartialEq)]
pub struct GameEvent {
    /// Type of game event.
    pub kind: GameEventKind,
    pub id: usize,
    pub _region_id: usize,
}

impl Ord for GameEvent {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.id.cmp(&other.id)
    }
}

impl PartialOrd for GameEvent {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(&other))
    }
}
impl Eq for GameEvent {}

#[derive(Debug, Copy, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum MouseButton {
    Left,
    Right,
    Middle,
}

#[derive(Debug, Copy, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum MouseButtonAction {
    Pressed,
    Released,
}

/// Game Event Kind
#[derive(Debug, Copy, Clone, Serialize, Deserialize, PartialEq)]
pub enum GameEventKind {
    /// A game tick
    Tick,
    MouseEvent(
        MouseButton,
        MouseButtonAction,
        (f32, f32),
        ((f32, f32, f32), (f32, f32, f32)),
    ),
    KeyboardEvent(u32),
    /// Stop the game and cleanup.
    Quit,
}

/// A region represents an portion of the world that processes game events at
/// its own tick rate separately from other regions.
pub struct Region {
    pub event_log: VecDeque<(GameEvent, Box<dyn Fn(&mut RegionData)>)>,
    input_buffer: BinaryHeap<Reverse<GameEvent>>,
    data: Arc<Mutex<RegionData>>,
}

#[derive(Debug)]
pub struct SnapshotEntity {
    position: Vector3<f32>,
    size: Vector3<f32>,
}

pub struct GameSnapshot {
    pub entities: Vec<SnapshotEntity>,
}

/// A word is a collection of regions that communicate with one another
/// via IPC.
pub struct World {
    regions: BTreeMap<usize, Region>,
    last_game_event_id: usize,
}

impl GameSnapshot {
    /// Build an empty game snapshot.
    pub fn new() -> Self {
        Self {
            entities: Vec::new(),
        }
    }

    /// Update the game snapshot with new data from simulation.
    pub fn apply_update(&mut self, _update: GameSnapshotUpdate) {}
}

#[derive(Debug)]
pub enum GameSnapshotUpdate {
    AddEntity(usize, SnapshotEntity),
    RemoveEntity(usize),
    SetEntity,
}

impl GameEvent {
    pub fn new(kind: GameEventKind, id: usize, _region_id: usize) -> Self {
        Self {
            kind,
            id,
            _region_id,
        }
    }
}

impl Region {
    /// Create new region
    pub fn new(data: Arc<Mutex<RegionData>>) -> Self {
        Self {
            data,
            event_log: VecDeque::new(),
            input_buffer: BinaryHeap::new(),
        }
    }

    /// Check if event from network matches client event history. rollback the
    /// game state as neccessary and re-simulate to current time.
    pub fn reconcile(&mut self, server_event: GameEvent) -> Result<(), GameError> {
        info!("input buffer {:?}", self.input_buffer);
        info!("incoming server event {:?}", server_event);
        self.input_buffer.push(Reverse(server_event));

        if self.input_buffer.len() > 10 {
            panic!("Server event input buffer too big.");
        }

        if self.event_log.len() == 0 {
            info!("adding to buffer {:?}", server_event);
            return Ok(());
        }

        let mut data = self.data.lock().unwrap();
        'outer: while let Some(server_event) = self.input_buffer.pop() {
            info!("comparing server event {:?}", server_event);
            while let Some((event, rollback)) = self.event_log.pop_front() {
                self.event_log.iter().for_each(|e| {
                    info!("rollback log: {:?}", e.0);
                });
                info!("popped event {:?}", event);
                if event.id == server_event.0.id {
                    // Events have the same ID, meaning this event is correctly
                    // next in order.
                    if event == server_event.0 {
                        // Incoming event is the same as event that was
                        // executed. Pure bliss.
                        info!("BLISS");
                        break;
                    } else {
                        rollback(&mut data);
                        // TODO: Discrepency detected.
                        // - store all events in rollback log into temp buffer
                        // - must rollback whole log
                        // - handle server event
                        // - re-apply all events from temp buffer.
                        todo!("Rollback is not implemented.");
                    }
                } else {
                    // IDs are incorrect, game event arrived out of order.
                    info!("Adding to input buffer.");
                    self.input_buffer.push(server_event);
                    break 'outer;
                }
            }
        }
        info!("FINISHED RECONCILING");
        Ok(())
    }

    /// Handle a client event.
    pub fn handle_event(&mut self, event: GameEvent) -> Result<(), GameError> {
        let mut t = Transaction::new(event, &mut self.event_log, self.data.lock().unwrap());
        match event.kind {
            GameEventKind::Tick => {
                info!("tick {:?}", t.r.data.tick);
                if t.r.data.entities.is_empty() {
                    t.create_text_entity("Hello, World!");
                }
                t.tick();
            }
            GameEventKind::Quit => todo!(),
            GameEventKind::MouseEvent(_button, _action, _screen_pos, _global_pos) => {
                info!("Recieved from window {:?}", event.kind);
            }
            GameEventKind::KeyboardEvent(id) => {
                info!("Recieved from window {:?}", id);
            }
        }
        //TODO: Temporary while reconciliation is off.
        t.event_log.clear();
        Ok(())
    }
}

struct Transaction<'a> {
    event: GameEvent,
    pub event_log: &'a mut VecDeque<(GameEvent, Box<dyn Fn(&mut RegionData)>)>,
    r: MutexGuard<'a, RegionData>,
}

impl<'a> Transaction<'a> {
    pub fn new(
        event: GameEvent,
        event_log: &'a mut VecDeque<(GameEvent, Box<dyn Fn(&mut RegionData)>)>,
        r: MutexGuard<'a, RegionData>,
    ) -> Self {
        Self {
            event,
            event_log,
            r,
        }
    }

    pub fn tick(&mut self) {
        self.event_log.push_back((
            self.event,
            Box::new(move |d| {
                d.data.tick -= 1;
            }),
        ));
        self.r.data.tick += 1;
    }

    pub fn create_text_entity(&mut self, text: &str) {
        let layout = text_layout(&mut self.r.font_context, text);
        let mut e = Entity::default();
        e.kind = EntityType::Text {
            content: text.to_string(),
        };
        let index = self.r.data.entities.len();
        self.r.data.entities.insert(index, e);
        self.r.text_layouts.insert(index, layout);
        self.event_log.push_back((
            self.event,
            Box::new(move |r| {
                r.text_layouts.remove(&index).unwrap();
                r.data.entities.remove(index);
            }),
        ));
    }

    pub fn _add_entity(&mut self, e: Entity) {
        let index = self.r.data.entities.len();
        self.r.data.entities.insert(index, e);
        self.event_log.push_back((
            self.event,
            Box::new(move |r| {
                r.data.entities.remove(index);
            }),
        ));
    }
}

impl World {
    pub fn new() -> Self {
        return Self {
            regions: BTreeMap::new(),
            last_game_event_id: 0,
        };
    }

    pub fn editor() -> Self {
        let data = Arc::new(Mutex::new(RegionData::new(
            GameData::new(),
            FontContext::new(),
        )));
        return Self {
            regions: BTreeMap::from([(0, Region::new(data))]),
            last_game_event_id: 0,
        };
    }

    pub fn clone_game_data(&self, id: &usize) -> GameData {
        self.regions
            .get(id)
            .unwrap()
            .data
            .clone()
            .try_lock()
            .unwrap()
            .data
            .clone()
    }

    pub fn load(&mut self, id: &usize, region: Region, last_game_event_id: usize) {
        self.last_game_event_id = last_game_event_id;
        self.regions.insert(*id, region);
    }

    pub fn handle_event(
        &mut self,
        event: GameEventKind,
        region_id: usize,
    ) -> Result<GameEvent, GameError> {
        let event = GameEvent::new(event, self.last_game_event_id, region_id);
        self.last_game_event_id += 1;
        let region = self.regions.get_mut(&event._region_id).unwrap();
        region.handle_event(event)?;
        Ok(event)
    }

    pub fn reconcile_event(&mut self, event: GameEvent) -> Result<(), GameError> {
        // self.regions
        //     .get_mut(&event._region_id)
        //     .unwrap()
        //     .reconcile(event)
        Ok(())
    }

    pub fn build_region_server_packet(&self, region_id: usize) -> ServerPacket {
        ServerPacket::Region(
            region_id,
            self.clone_game_data(&region_id),
            self.last_game_event_id,
        )
    }
}
