[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
game = { workspace = true }
slotmapd = { workspace = true }
crossbeam = { workspace = true }
simplelog = { workspace = true }
log = { workspace = true }
bincode = { workspace = true }
quinn = { workspace = true }
tokio = { workspace = true }
rcgen = { workspace = true }
dashmap = { workspace = true }
papaya = { workspace = true }
wtransport = { workspace = true }
pyroscope = { workspace = true, optional = true }
pyroscope_pprofrs = { workspace = true, optional = true }
