[package]
name = "nalgebra-macros"
version = "0.3.0"
authors = ["Andreas Longva", "Sébastien Crozet <developer@crozet.re>"]
edition = "2024"
description = "Procedural macros for nalgebra"
documentation = "https://www.nalgebra.rs/docs"
homepage = "https://nalgebra.rs"
repository = "https://github.com/dimforge/nalgebra"
readme = "../README.md"
categories = ["science", "mathematics"]
keywords = ["linear", "algebra", "matrix", "vector", "math"]
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true}
quote = {workspace = true}
proc-macro2 = {workspace = true}

[dev-dependencies]
nalgebra = { version = "0.34", path = ".." }
